//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CarServiceModel1", "SparePartsList", "RepairCards", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarService.DAL.RepairCard), "SpareParts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarService.DAL.SparePart))]

#endregion

namespace CarService.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CarServiceEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CarServiceEntities1 object using the connection string found in the 'CarServiceEntities1' section of the application configuration file.
        /// </summary>
        public CarServiceEntities1() : base("name=CarServiceEntities1", "CarServiceEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarServiceEntities1 object.
        /// </summary>
        public CarServiceEntities1(string connectionString) : base(connectionString, "CarServiceEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarServiceEntities1 object.
        /// </summary>
        public CarServiceEntities1(EntityConnection connection) : base(connection, "CarServiceEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RepairCard> RepairCards
        {
            get
            {
                if ((_RepairCards == null))
                {
                    _RepairCards = base.CreateObjectSet<RepairCard>("RepairCards");
                }
                return _RepairCards;
            }
        }
        private ObjectSet<RepairCard> _RepairCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SparePart> SpareParts
        {
            get
            {
                if ((_SpareParts == null))
                {
                    _SpareParts = base.CreateObjectSet<SparePart>("SpareParts");
                }
                return _SpareParts;
            }
        }
        private ObjectSet<SparePart> _SpareParts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RepairCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRepairCards(RepairCard repairCard)
        {
            base.AddObject("RepairCards", repairCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SpareParts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpareParts(SparePart sparePart)
        {
            base.AddObject("SpareParts", sparePart);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarServiceModel1", Name="RepairCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RepairCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RepairCard object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        /// <param name="carId">Initial value of the CarId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="partsPrice">Initial value of the PartsPrice property.</param>
        /// <param name="totalPrice">Initial value of the TotalPrice property.</param>
        public static RepairCard CreateRepairCard(global::System.Int32 id, global::System.DateTime entryDate, global::System.Int32 employeeId, global::System.Int32 carId, global::System.String description, global::System.Decimal partsPrice, global::System.Decimal totalPrice)
        {
            RepairCard repairCard = new RepairCard();
            repairCard.Id = id;
            repairCard.EntryDate = entryDate;
            repairCard.EmployeeId = employeeId;
            repairCard.CarId = carId;
            repairCard.Description = description;
            repairCard.PartsPrice = partsPrice;
            repairCard.TotalPrice = totalPrice;
            return repairCard;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value, "EntryDate");
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RepairFinishDate
        {
            get
            {
                return _RepairFinishDate;
            }
            set
            {
                OnRepairFinishDateChanging(value);
                ReportPropertyChanging("RepairFinishDate");
                _RepairFinishDate = StructuralObject.SetValidValue(value, "RepairFinishDate");
                ReportPropertyChanged("RepairFinishDate");
                OnRepairFinishDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RepairFinishDate;
        partial void OnRepairFinishDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRepairFinishDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value, "EmployeeId");
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarId
        {
            get
            {
                return _CarId;
            }
            set
            {
                OnCarIdChanging(value);
                ReportPropertyChanging("CarId");
                _CarId = StructuralObject.SetValidValue(value, "CarId");
                ReportPropertyChanged("CarId");
                OnCarIdChanged();
            }
        }
        private global::System.Int32 _CarId;
        partial void OnCarIdChanging(global::System.Int32 value);
        partial void OnCarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PartsPrice
        {
            get
            {
                return _PartsPrice;
            }
            set
            {
                OnPartsPriceChanging(value);
                ReportPropertyChanging("PartsPrice");
                _PartsPrice = StructuralObject.SetValidValue(value, "PartsPrice");
                ReportPropertyChanged("PartsPrice");
                OnPartsPriceChanged();
            }
        }
        private global::System.Decimal _PartsPrice;
        partial void OnPartsPriceChanging(global::System.Decimal value);
        partial void OnPartsPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value, "TotalPrice");
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private global::System.Decimal _TotalPrice;
        partial void OnTotalPriceChanging(global::System.Decimal value);
        partial void OnTotalPriceChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarServiceModel1", "SparePartsList", "SpareParts")]
        public EntityCollection<SparePart> SpareParts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SparePart>("CarServiceModel1.SparePartsList", "SpareParts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SparePart>("CarServiceModel1.SparePartsList", "SpareParts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarServiceModel1", Name="SparePart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SparePart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SparePart object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="partName">Initial value of the PartName property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="activated">Initial value of the Activated property.</param>
        public static SparePart CreateSparePart(global::System.Int32 id, global::System.String partName, global::System.Decimal price, global::System.Boolean activated)
        {
            SparePart sparePart = new SparePart();
            sparePart.Id = id;
            sparePart.PartName = partName;
            sparePart.Price = price;
            sparePart.Activated = activated;
            return sparePart;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PartName
        {
            get
            {
                return _PartName;
            }
            set
            {
                OnPartNameChanging(value);
                ReportPropertyChanging("PartName");
                _PartName = StructuralObject.SetValidValue(value, false, "PartName");
                ReportPropertyChanged("PartName");
                OnPartNameChanged();
            }
        }
        private global::System.String _PartName;
        partial void OnPartNameChanging(global::System.String value);
        partial void OnPartNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activated
        {
            get
            {
                return _Activated;
            }
            set
            {
                OnActivatedChanging(value);
                ReportPropertyChanging("Activated");
                _Activated = StructuralObject.SetValidValue(value, "Activated");
                ReportPropertyChanged("Activated");
                OnActivatedChanged();
            }
        }
        private global::System.Boolean _Activated;
        partial void OnActivatedChanging(global::System.Boolean value);
        partial void OnActivatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarServiceModel1", "SparePartsList", "RepairCards")]
        public EntityCollection<RepairCard> RepairCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RepairCard>("CarServiceModel1.SparePartsList", "RepairCards");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RepairCard>("CarServiceModel1.SparePartsList", "RepairCards", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
