//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("UserProfile")]
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Cars = new HashSet<Car>();
            this.Employees = new HashSet<Employee>();
            this.RepairCards = new HashSet<RepairCard>();
            this.SpareParts = new HashSet<SparePart>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }

        [Required]
        [Display(Name = "User")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "E-Mail")]
        public string Email { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<RepairCard> RepairCards { get; set; }
        public virtual ICollection<SparePart> SpareParts { get; set; }
    }
}
